---
- name: preflight
  import_tasks: preflight.yml

- name: Modify SELinux config
  when: _selinux_config.stat.exists
  block:
    - name: Install libselinux ansible module
      package:
        name: libselinux-python
        state: present
      become: yes
      # when: ansible_os_family == "RedHat"
      when: ansible_distribution == "CentOS"   # I want to verify this for other distros


    - name: Disable SELinux at next reboot
      selinux:
        state: disabled
      become: yes
      register: selinux_disabled

    - name: Set SELinux in permissive mode until the machine is rebooted
      shell: setenforce 0
      become: yes
      when: selinux_disabled.changed
      ignore_errors: True
