---
- name: preflight
  import_tasks: preflight.yml

- name: Modify SELinux config
  when: _selinux_config.stat.exists
  block:
    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      become: yes
      with_items: "{{ disable_selinux_dependencies }}"

    - name: Disable SELinux at next reboot
      selinux:
        state: disabled
      become: yes
      register: selinux_disabled

    - name: Set SELinux in permissive mode until the machine is rebooted
      shell: setenforce 0
      become: yes
      when: selinux_disabled.changed
      ignore_errors: True
