---
- name: Include OS specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- name: Check if SELinux config exists
  stat:
    path: /etc/selinux/config
  register: _selinux_config
